<?php

use Roomify\Bat\Constraint\MinMaxDaysConstraint;
use Roomify\Bat\Unit\Unit;
use Roomify\Bat\Event\Event;
use Roomify\Bat\Store\SqlDBStore;
use Roomify\Bat\Store\SqlLiteDBStore;
use Roomify\Bat\Calendar\Calendar;
use Roomify\Bat\Valuator\IntervalValuator;

require_once 'vendor/autoload.php';

try {
    /**
     * Create tables in tmp Sqlite DB
     */
    $pdo = new \PDO('sqlite::memory:');
    $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

    $pdo->exec("CREATE TABLE bat_event_availability_event_day_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'd1' INTEGER NOT NULL DEFAULT '0', 'd2' INTEGER NOT NULL DEFAULT '0', 'd3' INTEGER NOT NULL DEFAULT '0', 'd4' INTEGER NOT NULL DEFAULT '0', 'd5' INTEGER NOT NULL DEFAULT '0', 'd6' INTEGER NOT NULL DEFAULT '0', 'd7' INTEGER NOT NULL DEFAULT '0', 'd8' INTEGER NOT NULL DEFAULT '0', 'd9' INTEGER NOT NULL DEFAULT '0', 'd10' INTEGER NOT NULL DEFAULT '0', 'd11' INTEGER NOT NULL DEFAULT '0', 'd12' INTEGER NOT NULL DEFAULT '0', 'd13' INTEGER NOT NULL DEFAULT '0', 'd14' INTEGER NOT NULL DEFAULT '0', 'd15' INTEGER NOT NULL DEFAULT '0', 'd16' INTEGER NOT NULL DEFAULT '0', 'd17' INTEGER NOT NULL DEFAULT '0', 'd18' INTEGER NOT NULL DEFAULT '0', 'd19' INTEGER NOT NULL DEFAULT '0', 'd20' INTEGER NOT NULL DEFAULT '0', 'd21' INTEGER NOT NULL DEFAULT '0', 'd22' INTEGER NOT NULL DEFAULT '0', 'd23' INTEGER NOT NULL DEFAULT '0', 'd24' INTEGER NOT NULL DEFAULT '0', 'd25' INTEGER NOT NULL DEFAULT '0', 'd26' INTEGER NOT NULL DEFAULT '0', 'd27' INTEGER NOT NULL DEFAULT '0', 'd28' INTEGER NOT NULL DEFAULT '0', 'd29' INTEGER NOT NULL DEFAULT '0', 'd30' INTEGER NOT NULL DEFAULT '0', 'd31' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_availability_event_hour_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'h0' INTEGER NOT NULL DEFAULT '0', 'h1' INTEGER NOT NULL DEFAULT '0', 'h2' INTEGER NOT NULL DEFAULT '0', 'h3' INTEGER NOT NULL DEFAULT '0', 'h4' INTEGER NOT NULL DEFAULT '0', 'h5' INTEGER NOT NULL DEFAULT '0', 'h6' INTEGER NOT NULL DEFAULT '0', 'h7' INTEGER NOT NULL DEFAULT '0', 'h8' INTEGER NOT NULL DEFAULT '0', 'h9' INTEGER NOT NULL DEFAULT '0', 'h10' INTEGER NOT NULL DEFAULT '0', 'h11' INTEGER NOT NULL DEFAULT '0', 'h12' INTEGER NOT NULL DEFAULT '0', 'h13' INTEGER NOT NULL DEFAULT '0', 'h14' INTEGER NOT NULL DEFAULT '0',  'h15' INTEGER NOT NULL DEFAULT '0', 'h16' INTEGER NOT NULL DEFAULT '0', 'h17' INTEGER NOT NULL DEFAULT '0', 'h18' INTEGER NOT NULL DEFAULT '0', 'h19' INTEGER NOT NULL DEFAULT '0', 'h20' INTEGER NOT NULL DEFAULT '0', 'h21' INTEGER NOT NULL DEFAULT '0', 'h22' INTEGER NOT NULL DEFAULT '0', 'h23' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_availability_event_minute_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'hour' INTEGER NOT NULL DEFAULT '0', 'm00' INTEGER NOT NULL DEFAULT '0', 'm01' INTEGER NOT NULL DEFAULT '0', 'm02' INTEGER NOT NULL DEFAULT '0', 'm03' INTEGER NOT NULL DEFAULT '0', 'm04' INTEGER NOT NULL DEFAULT '0', 'm05' INTEGER NOT NULL DEFAULT '0', 'm06' INTEGER NOT NULL DEFAULT '0', 'm07' INTEGER NOT NULL DEFAULT '0', 'm08' INTEGER NOT NULL DEFAULT '0', 'm09' INTEGER NOT NULL DEFAULT '0', 'm10' INTEGER NOT NULL DEFAULT '0', 'm11' INTEGER NOT NULL DEFAULT '0', 'm12' INTEGER NOT NULL DEFAULT '0', 'm13' INTEGER NOT NULL DEFAULT '0', 'm14' INTEGER NOT NULL DEFAULT '0', 'm15' INTEGER NOT NULL DEFAULT '0', 'm16' INTEGER NOT NULL DEFAULT '0', 'm17' INTEGER NOT NULL DEFAULT '0', 'm18' INTEGER NOT NULL DEFAULT '0', 'm19' INTEGER NOT NULL DEFAULT '0', 'm20' INTEGER NOT NULL DEFAULT '0', 'm21' INTEGER NOT NULL DEFAULT '0', 'm22' INTEGER NOT NULL DEFAULT '0', 'm23' INTEGER NOT NULL DEFAULT '0', 'm24' INTEGER NOT NULL DEFAULT '0', 'm25' INTEGER NOT NULL DEFAULT '0', 'm26' INTEGER NOT NULL DEFAULT '0', 'm27' INTEGER NOT NULL DEFAULT '0', 'm28' INTEGER NOT NULL DEFAULT '0', 'm29' INTEGER NOT NULL DEFAULT '0', 'm30' INTEGER NOT NULL DEFAULT '0', 'm31' INTEGER NOT NULL DEFAULT '0', 'm32' INTEGER NOT NULL DEFAULT '0', 'm33' INTEGER NOT NULL DEFAULT '0', 'm34' INTEGER NOT NULL DEFAULT '0', 'm35' INTEGER NOT NULL DEFAULT '0', 'm36' INTEGER NOT NULL DEFAULT '0', 'm37' INTEGER NOT NULL DEFAULT '0', 'm38' INTEGER NOT NULL DEFAULT '0', 'm39' INTEGER NOT NULL DEFAULT '0', 'm40' INTEGER NOT NULL DEFAULT '0', 'm41' INTEGER NOT NULL DEFAULT '0', 'm42' INTEGER NOT NULL DEFAULT '0', 'm43' INTEGER NOT NULL DEFAULT '0', 'm44' INTEGER NOT NULL DEFAULT '0', 'm45' INTEGER NOT NULL DEFAULT '0', 'm46' INTEGER NOT NULL DEFAULT '0', 'm47' INTEGER NOT NULL DEFAULT '0', 'm48' INTEGER NOT NULL DEFAULT '0', 'm49' INTEGER NOT NULL DEFAULT '0', 'm50' INTEGER NOT NULL DEFAULT '0', 'm51' INTEGER NOT NULL DEFAULT '0', 'm52' INTEGER NOT NULL DEFAULT '0', 'm53' INTEGER NOT NULL DEFAULT '0', 'm54' INTEGER NOT NULL DEFAULT '0', 'm55' INTEGER NOT NULL DEFAULT '0', 'm56' INTEGER NOT NULL DEFAULT '0', 'm57' INTEGER NOT NULL DEFAULT '0', 'm58' INTEGER NOT NULL DEFAULT '0', 'm59' INTEGER NOT NULL DEFAULT '0')");

    $pdo->exec("CREATE TABLE bat_event_availability_event_day_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'd1' INTEGER NOT NULL DEFAULT '0', 'd2' INTEGER NOT NULL DEFAULT '0', 'd3' INTEGER NOT NULL DEFAULT '0', 'd4' INTEGER NOT NULL DEFAULT '0', 'd5' INTEGER NOT NULL DEFAULT '0', 'd6' INTEGER NOT NULL DEFAULT '0', 'd7' INTEGER NOT NULL DEFAULT '0', 'd8' INTEGER NOT NULL DEFAULT '0', 'd9' INTEGER NOT NULL DEFAULT '0', 'd10' INTEGER NOT NULL DEFAULT '0', 'd11' INTEGER NOT NULL DEFAULT '0', 'd12' INTEGER NOT NULL DEFAULT '0', 'd13' INTEGER NOT NULL DEFAULT '0', 'd14' INTEGER NOT NULL DEFAULT '0', 'd15' INTEGER NOT NULL DEFAULT '0', 'd16' INTEGER NOT NULL DEFAULT '0', 'd17' INTEGER NOT NULL DEFAULT '0', 'd18' INTEGER NOT NULL DEFAULT '0', 'd19' INTEGER NOT NULL DEFAULT '0', 'd20' INTEGER NOT NULL DEFAULT '0', 'd21' INTEGER NOT NULL DEFAULT '0', 'd22' INTEGER NOT NULL DEFAULT '0', 'd23' INTEGER NOT NULL DEFAULT '0', 'd24' INTEGER NOT NULL DEFAULT '0', 'd25' INTEGER NOT NULL DEFAULT '0', 'd26' INTEGER NOT NULL DEFAULT '0', 'd27' INTEGER NOT NULL DEFAULT '0', 'd28' INTEGER NOT NULL DEFAULT '0', 'd29' INTEGER NOT NULL DEFAULT '0', 'd30' INTEGER NOT NULL DEFAULT '0', 'd31' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_availability_event_hour_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'h0' INTEGER NOT NULL DEFAULT '0', 'h1' INTEGER NOT NULL DEFAULT '0', 'h2' INTEGER NOT NULL DEFAULT '0', 'h3' INTEGER NOT NULL DEFAULT '0', 'h4' INTEGER NOT NULL DEFAULT '0', 'h5' INTEGER NOT NULL DEFAULT '0', 'h6' INTEGER NOT NULL DEFAULT '0', 'h7' INTEGER NOT NULL DEFAULT '0', 'h8' INTEGER NOT NULL DEFAULT '0', 'h9' INTEGER NOT NULL DEFAULT '0', 'h10' INTEGER NOT NULL DEFAULT '0', 'h11' INTEGER NOT NULL DEFAULT '0', 'h12' INTEGER NOT NULL DEFAULT '0', 'h13' INTEGER NOT NULL DEFAULT '0', 'h14' INTEGER NOT NULL DEFAULT '0',  'h15' INTEGER NOT NULL DEFAULT '0', 'h16' INTEGER NOT NULL DEFAULT '0', 'h17' INTEGER NOT NULL DEFAULT '0', 'h18' INTEGER NOT NULL DEFAULT '0', 'h19' INTEGER NOT NULL DEFAULT '0', 'h20' INTEGER NOT NULL DEFAULT '0', 'h21' INTEGER NOT NULL DEFAULT '0', 'h22' INTEGER NOT NULL DEFAULT '0', 'h23' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_availability_event_minute_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'hour' INTEGER NOT NULL DEFAULT '0', 'm00' INTEGER NOT NULL DEFAULT '0', 'm01' INTEGER NOT NULL DEFAULT '0', 'm02' INTEGER NOT NULL DEFAULT '0', 'm03' INTEGER NOT NULL DEFAULT '0', 'm04' INTEGER NOT NULL DEFAULT '0', 'm05' INTEGER NOT NULL DEFAULT '0', 'm06' INTEGER NOT NULL DEFAULT '0', 'm07' INTEGER NOT NULL DEFAULT '0', 'm08' INTEGER NOT NULL DEFAULT '0', 'm09' INTEGER NOT NULL DEFAULT '0', 'm10' INTEGER NOT NULL DEFAULT '0', 'm11' INTEGER NOT NULL DEFAULT '0', 'm12' INTEGER NOT NULL DEFAULT '0', 'm13' INTEGER NOT NULL DEFAULT '0', 'm14' INTEGER NOT NULL DEFAULT '0', 'm15' INTEGER NOT NULL DEFAULT '0', 'm16' INTEGER NOT NULL DEFAULT '0', 'm17' INTEGER NOT NULL DEFAULT '0', 'm18' INTEGER NOT NULL DEFAULT '0', 'm19' INTEGER NOT NULL DEFAULT '0', 'm20' INTEGER NOT NULL DEFAULT '0', 'm21' INTEGER NOT NULL DEFAULT '0', 'm22' INTEGER NOT NULL DEFAULT '0', 'm23' INTEGER NOT NULL DEFAULT '0', 'm24' INTEGER NOT NULL DEFAULT '0', 'm25' INTEGER NOT NULL DEFAULT '0', 'm26' INTEGER NOT NULL DEFAULT '0', 'm27' INTEGER NOT NULL DEFAULT '0', 'm28' INTEGER NOT NULL DEFAULT '0', 'm29' INTEGER NOT NULL DEFAULT '0', 'm30' INTEGER NOT NULL DEFAULT '0', 'm31' INTEGER NOT NULL DEFAULT '0', 'm32' INTEGER NOT NULL DEFAULT '0', 'm33' INTEGER NOT NULL DEFAULT '0', 'm34' INTEGER NOT NULL DEFAULT '0', 'm35' INTEGER NOT NULL DEFAULT '0', 'm36' INTEGER NOT NULL DEFAULT '0', 'm37' INTEGER NOT NULL DEFAULT '0', 'm38' INTEGER NOT NULL DEFAULT '0', 'm39' INTEGER NOT NULL DEFAULT '0', 'm40' INTEGER NOT NULL DEFAULT '0', 'm41' INTEGER NOT NULL DEFAULT '0', 'm42' INTEGER NOT NULL DEFAULT '0', 'm43' INTEGER NOT NULL DEFAULT '0', 'm44' INTEGER NOT NULL DEFAULT '0', 'm45' INTEGER NOT NULL DEFAULT '0', 'm46' INTEGER NOT NULL DEFAULT '0', 'm47' INTEGER NOT NULL DEFAULT '0', 'm48' INTEGER NOT NULL DEFAULT '0', 'm49' INTEGER NOT NULL DEFAULT '0', 'm50' INTEGER NOT NULL DEFAULT '0', 'm51' INTEGER NOT NULL DEFAULT '0', 'm52' INTEGER NOT NULL DEFAULT '0', 'm53' INTEGER NOT NULL DEFAULT '0', 'm54' INTEGER NOT NULL DEFAULT '0', 'm55' INTEGER NOT NULL DEFAULT '0', 'm56' INTEGER NOT NULL DEFAULT '0', 'm57' INTEGER NOT NULL DEFAULT '0', 'm58' INTEGER NOT NULL DEFAULT '0', 'm59' INTEGER NOT NULL DEFAULT '0')");

    $pdo->exec("CREATE TABLE bat_event_price_event_day_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'd1' INTEGER NOT NULL DEFAULT '0', 'd2' INTEGER NOT NULL DEFAULT '0', 'd3' INTEGER NOT NULL DEFAULT '0', 'd4' INTEGER NOT NULL DEFAULT '0', 'd5' INTEGER NOT NULL DEFAULT '0', 'd6' INTEGER NOT NULL DEFAULT '0', 'd7' INTEGER NOT NULL DEFAULT '0', 'd8' INTEGER NOT NULL DEFAULT '0', 'd9' INTEGER NOT NULL DEFAULT '0', 'd10' INTEGER NOT NULL DEFAULT '0', 'd11' INTEGER NOT NULL DEFAULT '0', 'd12' INTEGER NOT NULL DEFAULT '0', 'd13' INTEGER NOT NULL DEFAULT '0', 'd14' INTEGER NOT NULL DEFAULT '0', 'd15' INTEGER NOT NULL DEFAULT '0', 'd16' INTEGER NOT NULL DEFAULT '0', 'd17' INTEGER NOT NULL DEFAULT '0', 'd18' INTEGER NOT NULL DEFAULT '0', 'd19' INTEGER NOT NULL DEFAULT '0', 'd20' INTEGER NOT NULL DEFAULT '0', 'd21' INTEGER NOT NULL DEFAULT '0', 'd22' INTEGER NOT NULL DEFAULT '0', 'd23' INTEGER NOT NULL DEFAULT '0', 'd24' INTEGER NOT NULL DEFAULT '0', 'd25' INTEGER NOT NULL DEFAULT '0', 'd26' INTEGER NOT NULL DEFAULT '0', 'd27' INTEGER NOT NULL DEFAULT '0', 'd28' INTEGER NOT NULL DEFAULT '0', 'd29' INTEGER NOT NULL DEFAULT '0', 'd30' INTEGER NOT NULL DEFAULT '0', 'd31' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_price_event_hour_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'h0' INTEGER NOT NULL DEFAULT '0', 'h1' INTEGER NOT NULL DEFAULT '0', 'h2' INTEGER NOT NULL DEFAULT '0', 'h3' INTEGER NOT NULL DEFAULT '0', 'h4' INTEGER NOT NULL DEFAULT '0', 'h5' INTEGER NOT NULL DEFAULT '0', 'h6' INTEGER NOT NULL DEFAULT '0', 'h7' INTEGER NOT NULL DEFAULT '0', 'h8' INTEGER NOT NULL DEFAULT '0', 'h9' INTEGER NOT NULL DEFAULT '0', 'h10' INTEGER NOT NULL DEFAULT '0', 'h11' INTEGER NOT NULL DEFAULT '0', 'h12' INTEGER NOT NULL DEFAULT '0', 'h13' INTEGER NOT NULL DEFAULT '0', 'h14' INTEGER NOT NULL DEFAULT '0',  'h15' INTEGER NOT NULL DEFAULT '0', 'h16' INTEGER NOT NULL DEFAULT '0', 'h17' INTEGER NOT NULL DEFAULT '0', 'h18' INTEGER NOT NULL DEFAULT '0', 'h19' INTEGER NOT NULL DEFAULT '0', 'h20' INTEGER NOT NULL DEFAULT '0', 'h21' INTEGER NOT NULL DEFAULT '0', 'h22' INTEGER NOT NULL DEFAULT '0', 'h23' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_price_event_minute_event ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'hour' INTEGER NOT NULL DEFAULT '0', 'm00' INTEGER NOT NULL DEFAULT '0', 'm01' INTEGER NOT NULL DEFAULT '0', 'm02' INTEGER NOT NULL DEFAULT '0', 'm03' INTEGER NOT NULL DEFAULT '0', 'm04' INTEGER NOT NULL DEFAULT '0', 'm05' INTEGER NOT NULL DEFAULT '0', 'm06' INTEGER NOT NULL DEFAULT '0', 'm07' INTEGER NOT NULL DEFAULT '0', 'm08' INTEGER NOT NULL DEFAULT '0', 'm09' INTEGER NOT NULL DEFAULT '0', 'm10' INTEGER NOT NULL DEFAULT '0', 'm11' INTEGER NOT NULL DEFAULT '0', 'm12' INTEGER NOT NULL DEFAULT '0', 'm13' INTEGER NOT NULL DEFAULT '0', 'm14' INTEGER NOT NULL DEFAULT '0', 'm15' INTEGER NOT NULL DEFAULT '0', 'm16' INTEGER NOT NULL DEFAULT '0', 'm17' INTEGER NOT NULL DEFAULT '0', 'm18' INTEGER NOT NULL DEFAULT '0', 'm19' INTEGER NOT NULL DEFAULT '0', 'm20' INTEGER NOT NULL DEFAULT '0', 'm21' INTEGER NOT NULL DEFAULT '0', 'm22' INTEGER NOT NULL DEFAULT '0', 'm23' INTEGER NOT NULL DEFAULT '0', 'm24' INTEGER NOT NULL DEFAULT '0', 'm25' INTEGER NOT NULL DEFAULT '0', 'm26' INTEGER NOT NULL DEFAULT '0', 'm27' INTEGER NOT NULL DEFAULT '0', 'm28' INTEGER NOT NULL DEFAULT '0', 'm29' INTEGER NOT NULL DEFAULT '0', 'm30' INTEGER NOT NULL DEFAULT '0', 'm31' INTEGER NOT NULL DEFAULT '0', 'm32' INTEGER NOT NULL DEFAULT '0', 'm33' INTEGER NOT NULL DEFAULT '0', 'm34' INTEGER NOT NULL DEFAULT '0', 'm35' INTEGER NOT NULL DEFAULT '0', 'm36' INTEGER NOT NULL DEFAULT '0', 'm37' INTEGER NOT NULL DEFAULT '0', 'm38' INTEGER NOT NULL DEFAULT '0', 'm39' INTEGER NOT NULL DEFAULT '0', 'm40' INTEGER NOT NULL DEFAULT '0', 'm41' INTEGER NOT NULL DEFAULT '0', 'm42' INTEGER NOT NULL DEFAULT '0', 'm43' INTEGER NOT NULL DEFAULT '0', 'm44' INTEGER NOT NULL DEFAULT '0', 'm45' INTEGER NOT NULL DEFAULT '0', 'm46' INTEGER NOT NULL DEFAULT '0', 'm47' INTEGER NOT NULL DEFAULT '0', 'm48' INTEGER NOT NULL DEFAULT '0', 'm49' INTEGER NOT NULL DEFAULT '0', 'm50' INTEGER NOT NULL DEFAULT '0', 'm51' INTEGER NOT NULL DEFAULT '0', 'm52' INTEGER NOT NULL DEFAULT '0', 'm53' INTEGER NOT NULL DEFAULT '0', 'm54' INTEGER NOT NULL DEFAULT '0', 'm55' INTEGER NOT NULL DEFAULT '0', 'm56' INTEGER NOT NULL DEFAULT '0', 'm57' INTEGER NOT NULL DEFAULT '0', 'm58' INTEGER NOT NULL DEFAULT '0', 'm59' INTEGER NOT NULL DEFAULT '0')");

    $pdo->exec("CREATE TABLE bat_event_price_event_day_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'd1' INTEGER NOT NULL DEFAULT '0', 'd2' INTEGER NOT NULL DEFAULT '0', 'd3' INTEGER NOT NULL DEFAULT '0', 'd4' INTEGER NOT NULL DEFAULT '0', 'd5' INTEGER NOT NULL DEFAULT '0', 'd6' INTEGER NOT NULL DEFAULT '0', 'd7' INTEGER NOT NULL DEFAULT '0', 'd8' INTEGER NOT NULL DEFAULT '0', 'd9' INTEGER NOT NULL DEFAULT '0', 'd10' INTEGER NOT NULL DEFAULT '0', 'd11' INTEGER NOT NULL DEFAULT '0', 'd12' INTEGER NOT NULL DEFAULT '0', 'd13' INTEGER NOT NULL DEFAULT '0', 'd14' INTEGER NOT NULL DEFAULT '0', 'd15' INTEGER NOT NULL DEFAULT '0', 'd16' INTEGER NOT NULL DEFAULT '0', 'd17' INTEGER NOT NULL DEFAULT '0', 'd18' INTEGER NOT NULL DEFAULT '0', 'd19' INTEGER NOT NULL DEFAULT '0', 'd20' INTEGER NOT NULL DEFAULT '0', 'd21' INTEGER NOT NULL DEFAULT '0', 'd22' INTEGER NOT NULL DEFAULT '0', 'd23' INTEGER NOT NULL DEFAULT '0', 'd24' INTEGER NOT NULL DEFAULT '0', 'd25' INTEGER NOT NULL DEFAULT '0', 'd26' INTEGER NOT NULL DEFAULT '0', 'd27' INTEGER NOT NULL DEFAULT '0', 'd28' INTEGER NOT NULL DEFAULT '0', 'd29' INTEGER NOT NULL DEFAULT '0', 'd30' INTEGER NOT NULL DEFAULT '0', 'd31' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_price_event_hour_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'h0' INTEGER NOT NULL DEFAULT '0', 'h1' INTEGER NOT NULL DEFAULT '0', 'h2' INTEGER NOT NULL DEFAULT '0', 'h3' INTEGER NOT NULL DEFAULT '0', 'h4' INTEGER NOT NULL DEFAULT '0', 'h5' INTEGER NOT NULL DEFAULT '0', 'h6' INTEGER NOT NULL DEFAULT '0', 'h7' INTEGER NOT NULL DEFAULT '0', 'h8' INTEGER NOT NULL DEFAULT '0', 'h9' INTEGER NOT NULL DEFAULT '0', 'h10' INTEGER NOT NULL DEFAULT '0', 'h11' INTEGER NOT NULL DEFAULT '0', 'h12' INTEGER NOT NULL DEFAULT '0', 'h13' INTEGER NOT NULL DEFAULT '0', 'h14' INTEGER NOT NULL DEFAULT '0',  'h15' INTEGER NOT NULL DEFAULT '0', 'h16' INTEGER NOT NULL DEFAULT '0', 'h17' INTEGER NOT NULL DEFAULT '0', 'h18' INTEGER NOT NULL DEFAULT '0', 'h19' INTEGER NOT NULL DEFAULT '0', 'h20' INTEGER NOT NULL DEFAULT '0', 'h21' INTEGER NOT NULL DEFAULT '0', 'h22' INTEGER NOT NULL DEFAULT '0', 'h23' INTEGER NOT NULL DEFAULT '0')");
    $pdo->exec("CREATE TABLE bat_event_price_event_minute_state ('unit_id' INTEGER NOT NULL, 'year' INTEGER NOT NULL DEFAULT '0', 'month' INTEGER NOT NULL DEFAULT '0', 'day' INTEGER NOT NULL DEFAULT '0', 'hour' INTEGER NOT NULL DEFAULT '0', 'm00' INTEGER NOT NULL DEFAULT '0', 'm01' INTEGER NOT NULL DEFAULT '0', 'm02' INTEGER NOT NULL DEFAULT '0', 'm03' INTEGER NOT NULL DEFAULT '0', 'm04' INTEGER NOT NULL DEFAULT '0', 'm05' INTEGER NOT NULL DEFAULT '0', 'm06' INTEGER NOT NULL DEFAULT '0', 'm07' INTEGER NOT NULL DEFAULT '0', 'm08' INTEGER NOT NULL DEFAULT '0', 'm09' INTEGER NOT NULL DEFAULT '0', 'm10' INTEGER NOT NULL DEFAULT '0', 'm11' INTEGER NOT NULL DEFAULT '0', 'm12' INTEGER NOT NULL DEFAULT '0', 'm13' INTEGER NOT NULL DEFAULT '0', 'm14' INTEGER NOT NULL DEFAULT '0', 'm15' INTEGER NOT NULL DEFAULT '0', 'm16' INTEGER NOT NULL DEFAULT '0', 'm17' INTEGER NOT NULL DEFAULT '0', 'm18' INTEGER NOT NULL DEFAULT '0', 'm19' INTEGER NOT NULL DEFAULT '0', 'm20' INTEGER NOT NULL DEFAULT '0', 'm21' INTEGER NOT NULL DEFAULT '0', 'm22' INTEGER NOT NULL DEFAULT '0', 'm23' INTEGER NOT NULL DEFAULT '0', 'm24' INTEGER NOT NULL DEFAULT '0', 'm25' INTEGER NOT NULL DEFAULT '0', 'm26' INTEGER NOT NULL DEFAULT '0', 'm27' INTEGER NOT NULL DEFAULT '0', 'm28' INTEGER NOT NULL DEFAULT '0', 'm29' INTEGER NOT NULL DEFAULT '0', 'm30' INTEGER NOT NULL DEFAULT '0', 'm31' INTEGER NOT NULL DEFAULT '0', 'm32' INTEGER NOT NULL DEFAULT '0', 'm33' INTEGER NOT NULL DEFAULT '0', 'm34' INTEGER NOT NULL DEFAULT '0', 'm35' INTEGER NOT NULL DEFAULT '0', 'm36' INTEGER NOT NULL DEFAULT '0', 'm37' INTEGER NOT NULL DEFAULT '0', 'm38' INTEGER NOT NULL DEFAULT '0', 'm39' INTEGER NOT NULL DEFAULT '0', 'm40' INTEGER NOT NULL DEFAULT '0', 'm41' INTEGER NOT NULL DEFAULT '0', 'm42' INTEGER NOT NULL DEFAULT '0', 'm43' INTEGER NOT NULL DEFAULT '0', 'm44' INTEGER NOT NULL DEFAULT '0', 'm45' INTEGER NOT NULL DEFAULT '0', 'm46' INTEGER NOT NULL DEFAULT '0', 'm47' INTEGER NOT NULL DEFAULT '0', 'm48' INTEGER NOT NULL DEFAULT '0', 'm49' INTEGER NOT NULL DEFAULT '0', 'm50' INTEGER NOT NULL DEFAULT '0', 'm51' INTEGER NOT NULL DEFAULT '0', 'm52' INTEGER NOT NULL DEFAULT '0', 'm53' INTEGER NOT NULL DEFAULT '0', 'm54' INTEGER NOT NULL DEFAULT '0', 'm55' INTEGER NOT NULL DEFAULT '0', 'm56' INTEGER NOT NULL DEFAULT '0', 'm57' INTEGER NOT NULL DEFAULT '0', 'm58' INTEGER NOT NULL DEFAULT '0', 'm59' INTEGER NOT NULL DEFAULT '0')");

    /**
     * DB table for availability event
     */
    $availability_store = new SqlLiteDBStore($pdo, 'availability_event', SqlDBStore::BAT_STATE);

    /**
     * DB table for price event
     */
    $price_store = new SqlLiteDBStore($pdo, 'price_event', SqlDBStore::BAT_STATE);

    /**
     * ROOMS
     */
    $ROOM_FREE = 1;
    $ROOM_BOOKED = 2;

    /**
     * Create 3 rooms
     * Rooms are available by default
     */
    $constraint = new MinMaxDaysConstraint(array(), 0, false);
    $room_1 = new Unit(1, $ROOM_FREE, array($constraint));

    $constraint = new MinMaxDaysConstraint(array(), 0, false);
    $room_2 = new Unit(2, $ROOM_FREE, array($constraint));

    $constraint = new MinMaxDaysConstraint(array(), 0, false);
    $room_3 = new Unit(3, $ROOM_FREE, array($constraint));

    /**
     * Create Calendar for created Rooms
     */
    $state_calendar = new Calendar(array($room_1, $room_2, $room_3), $availability_store);

    $search_from = new \DateTime('2016-01-01 8:00');
    $search_to =  new \DateTime('2016-01-01 22:00');

    /**
     * Get all available Rooms for given period of time
     */
    $available_rooms = $state_calendar->getMatchingUnits($search_from, $search_to, array($ROOM_FREE), array());

    echo "\nAvailable Rooms: ".count($available_rooms->getIncluded())."\n";
    foreach ($available_rooms->getIncluded() as $res) {
        echo "Room #{$res['unit']->getUnitId()}\n";
    }

    /**
     * Create reservations for Room 1 and 2
     */
    $av_event = new Event(new \DateTime('2016-01-01 8:00'), new \DateTime('2016-01-01 11:59'), $room_1, $ROOM_BOOKED);
    $state_calendar->addEvents(array($av_event), Event::BAT_HOURLY);

    $av_event2 = new Event(new \DateTime('2016-01-01 12:00'), new \DateTime('2016-01-01 13:59'), $room_2, $ROOM_BOOKED);
    $state_calendar->addEvents(array($av_event2), Event::BAT_HOURLY);

    /**
     * Search again : one Room available for whole day
     */
    $available_rooms = $state_calendar->getMatchingUnits($search_from, $search_to, array($ROOM_FREE), array());

    echo "\nAvailable Rooms: ".count($available_rooms->getIncluded())."\n";
    foreach ($available_rooms->getIncluded() as $res) {
        echo "Room #{$res['unit']->getUnitId()}\n";
    }

    /**
     * Search again from 12:00 - 22:00 : 2 Rooms available
     */
    $available_rooms = $state_calendar->getMatchingUnits(new \DateTime('2016-01-01 12:00'), $search_to, array($ROOM_FREE), array());

    echo "\nAvailable Rooms: ".count($available_rooms->getIncluded())."\n";
    foreach ($available_rooms->getIncluded() as $res) {
        echo "Room #{$res['unit']->getUnitId()}\n";
    }

    /**
     * CALENDAR
     *
     * Print calendar with all Rooms with availability indication
     * x - free
     * _ - booked
     */
    echo "\nCalendar:\n";

    echo "------- DATE --------- ROOM 1 -- ROOM 2 -- ROOM 3\n";

    $begin = new DateTime('2016-01-01 6:00');
    $end = new DateTime('2016-01-2 22:00');

    $interval = DateInterval::createFromDateString('1 hour');
    $period = new DatePeriod($begin, $interval, $end);

    foreach ($period as $dt) {
        /**
         * Skip night hours for now
         */
        if (!in_array($dt->format('H'), range(6, 22))) {
            continue;
        }

        $from = clone($dt);
        $to =  $dt->modify('+59 minutes');
        $available_rooms = $state_calendar->getMatchingUnits($from, $to, array($ROOM_FREE), array());

        $av = $available_rooms->getIncluded();

        echo $dt->format("Y-m-d H:i:s --- ".(isset($av[1]) ? 'x' : ' ')." ------- ".(isset($av[2]) ? 'x' : ' ')." ------- ".(isset($av[3]) ? 'x' : ' ')."\n");
    }
    echo "\n";

    /**
     * PRICING
     */
    echo "Pricing:\n";

    /**
     * Set prices for different day parts
     *
     * Morning: 100 default
     * Evening: 150
     * Weekend: 200
     */
    $PRICE_MORNING = 100;
    $PRICE_EVENING = 150;
    $PRICE_WEEKEND = 200;

    /**
     * Calendar
     */
    $state_calendar = new Calendar(array($room_1), $price_store);

    /**
     * Set pricing for Room 1
     */
    $room_1->setDefaultValue($PRICE_MORNING);

    $price_evening = new Event(new \DateTime('2016-01-01 18:00'), new \DateTime('2016-01-01 22:00'), $room_1, $PRICE_EVENING);
    $state_calendar->addEvents(array($price_evening), Event::BAT_HOURLY);

    $price_weekend = new Event(new \DateTime('2016-01-02 6:00'), new \DateTime('2016-01-02 22:00'), $room_1, $PRICE_WEEKEND);
    $state_calendar->addEvents(array($price_weekend), Event::BAT_HOURLY);

    /**
     * Pricing 1
     * 6h morning only : 600 (6*100)
     */
    $date_from = '2016-01-01 6:00';
    $date_to = '2016-01-01 11:59';
    $valuator = new IntervalValuator(
        new \DateTime($date_from),
        new \DateTime($date_to),
        $room_1,
        $price_store,
        new \DateInterval('PT1H')
    );

    echo "Price 1 for {$date_from} - {$date_to} : {$valuator->determineValue()}\n";

    /**
     * Pricing 2
     * 5h - 2h morning + 3h evening  : 650 (2*100+3*150)
     */
    $date_from = '2016-01-01 16:00';
    $date_to = '2016-01-01 20:59';
    $valuator = new IntervalValuator(
        new \DateTime($date_from),
        new \DateTime($date_to),
        $room_1,
        $price_store,
        new \DateInterval('PT1H')
    );

    echo "Price 2 for {$date_from} - {$date_to} : {$valuator->determineValue()}\n";

    /**
     * Pricing 3
     * 4h weekend  : 800 (4*200)
     */
    $date_from = '2016-01-02 16:00';
    $date_to = '2016-01-02 19:59';
    $valuator = new IntervalValuator(
        new \DateTime($date_from),
        new \DateTime($date_to),
        $room_1,
        $price_store,
        new \DateInterval('PT1H')
    );

    echo "Price 2 for {$date_from} - {$date_to} : {$valuator->determineValue()}\n";

} catch (PDOException $e) {
    echo $e->getMessage();
}
